### ISSUE TITLE
Converting to exe with PS2EXE gives unwanted output.

### ISSUE THREAD

**Issue by Solbstr** [Tiberriver256/PoshProgressBar#11]
Hello Micah Rairdon

When using this progress bar in script (and converting to exe with 'ps2exe gui' i get an output after "close-progressbar". Is it possible to disable the output getting written to the console? 

I also experience the "converted exe to remain in task manager" after the program has ended.

Output:
Dispatcher : System.Windows.Threading.Dispatcher
Priority : Normal
Status : Executing
Task : System.Threading.Tasks.Task`1[System.Object]
Result :

PS2EXE: 
https://gallery.technet.microsoft.com/scriptcenter/PS2EXE-GUI-Convert-e7cb69d5

ProgressBar verion:
https://github.com/Tiberriver256/PoshProgressBar/tree/master/PoshProgressBar

Greetings
Nils,

**Comment by Tiberriver256** [comment]
Sorry, I didn't realize closing that PR would auto-close the issue. Would you mind downloading and verifying you're not seeing the output anymore for me? Then I'll republish to the Gallery.

**Comment by Solbstr** [comment]
Hi

Still getting the same output when running script in PowerShell or script converted to EXE.

Dispatcher : System.Windows.Threading.Dispatcher
Priority   : Normal
Status     : Executing
Task       : System.Threading.Tasks.Task`1[System.Object]
Result     : 

When running script converted to EXE the EXE remains running in taskmanager.

**Comment by Tiberriver256** [comment]
Bah, sorry about that. Looks like it was more involved than I thought. Can you re-pull and test again for me?

I had to close a bit differently via #13

**Comment by nilssol** [comment]
I pulled code from  : https://github.com/Tiberriver256/PoshProgressBar/pull/13
Now the bar stays on 100% and dosent close.

**Comment by Solbstr** [comment]
Greate, looks like the output now is gone and fixed.
But when converting to PowerShell script to EXE , after running the EXE progress bar closes like it should but the EXE remains active in task manager.

Nils

**Comment by Tiberriver256** [comment]
Apologies for taking so long to reply. I'm not too familiar with PS2EXE you may want to make sure it's compiling with runtime version 4 and not using PowerShell v2?

Beyond that I would recommend you possibly open an issue on the ps2exe repo for further assistance.
